FROM fuww/nginx-pagespeed:latest
# FROM landing-pages-proxy:latest

# Please mind, Adding SSL will add a lot of startup time
ENV SSL_ENABLED false

COPY ./etc /etc
# COPY dist /usr/html

# CMD ["/sbin/my_init"]
