apiVersion: skaffold/v1beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: eu.gcr.io/private-fashionunited-registry/hugo-amp-testje
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/hugo.deployment.yaml
      - kubernetes-manifests/hugo.service.yaml
