# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "AMP"
license = "MIT"
licenselink = "https://github.com/Acme/amp/blob/master/LICENSE"
description = "AMP supporting theme for Hugo"
homepage = "https://amp.Acme.com"
tags = ["blog", "amp", "accelerated mobile pages", "seo", "starter"]
features = ["amp","accelerated mobile pages","structured data","shortcodes","partials","seo","schema"]
min_version = 0.17

[author]
    name = "Joost van der Laan"
    homepage = "https://github.com/joostvanderlaan"
